/**
 * Nightly: crawl all enabled sources (network only — no model in memory),
 * then hand off to the orchestrator to classify/embed everything queued.
 * (Story candidates are generated by the separate job:stories run — see
 * scripts/nightly-story-candidates.ts.)
 * Run via: pnpm --filter web run job:nightly
 */
import "./env";
import { spawnSync } from "node:child_process";
import { db } from "../apps/web/src/db/client";
import { crawlAllSources } from "../apps/web/src/lib/crawl";
import { extractJournalFromChat } from "../apps/web/src/lib/skills/journal";

const main = async () => {
  console.log(`nightly pipeline starting ${new Date().toISOString()}`);
  const summaries = await crawlAllSources(db);
  for (const s of summaries) {
    console.log(
      `crawl ${s.slug}: ${s.inserted} new / ${s.seen} seen${s.error ? ` — ERROR: ${s.error}` : ""}`,
    );
  }

  try {
    console.log(await extractJournalFromChat(db));
  } catch (err) {
    console.error(`journal extraction failed: ${err instanceof Error ? err.message : err}`);
  }

  // Same process would also work, but exec keeps run-jobs the single code path.
  const res = spawnSync("pnpm", ["tsx", "../../scripts/run-jobs.ts"], {
    cwd: process.cwd(), // apps/web
    stdio: "inherit",
    env: process.env,
    timeout: 2 * 60 * 60 * 1000,
  });
  process.exit(res.status ?? 0);
};

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
